### ISSUE TITLE
Incorrect value in Temporary Access Pass settings

### ISSUE THREAD

**Issue by peterb-bne** [ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud#18]
https://github.com/ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud/tree/main/content/en/configuration/entra-id/protection/authentication-methods/policies.md

In the Temporary Access Pass Settings / Configure table, you have the One-time value as 14, however it is a yes/no toggle button.  I'm assuming the 14 refers to the length setting which isn't in the table but probably should be.

**Comment by JollyRaccoon4** [comment]
Thanks @peterb-bne and many apologies for the rather significant delay in response - the last while has gotten away from us as we were working on the latest updates. Indeed, this was a misalignment in the table values. We have addressed this in yesterday's update - please check out the page again which should read more clearly.
