### ISSUE TITLE
iOS compliance policy table is incorrect

### ISSUE THREAD

**Issue by martincaddick** [ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud#19]
https://github.com/ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud/blob/main/content/en/configuration/intune/devices/compliance-policies/policies/apple-ios-and-ipad.md#system-security

Looks like misalignment in the table. (Password expiry and previous passwords used)

**Comment by JollyRaccoon4** [comment]
Thanks Martin. Can confirm this is a misalignment. We've added it to our list of fixes/updates for correction in an upcoming release of the Blueprint.

**Comment by JollyRaccoon4** [comment]
Hi @martincaddick - the fix for this has made it into our version released yesterday (v1.2.1) - please continue to let us know if there are any other issues you notice.
