### ISSUE TITLE
Q. Configuration table interpretation

### ISSUE THREAD

**Issue by martincaddick** [ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud#24]
I'm trying to interpret the configuration tables (which are pretty awesome by the way). Formatting is a huge part of the consistency with the two column tables of Item and Value being very easy to use.

Is it reasonable to assume that if the text in the Item column is **bold** and if it has no corresponding Value then it is a table subheading like Locations in the screenshot below? And that if it does have a corresponding Value then it should be treated as a consolidated setting?

Cheers

![image](https://github.com/ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud/assets/73564857/f1e533fd-2f35-46cc-b0b5-7bb45c8b6326)

**Comment by RebelliousBadger** [comment]
Hi Martin

Sorry for the delay in replying! Your interpretation of the configuration table is correct, where there is a bold text in the Item column with no corresponding Value this denotes a sub-heading. However, noting there is potential for this to still cause some confusion, we have added your feedback to our list of fixes/updates and will use it to improve the readability and formatting of configuration tables in a future release of the Blueprint.

Please continue to reach out if you have any further feedback or enquiries. Thanks!
