### ISSUE TITLE
Change log does not include changes from the DTA Blueprint v2112

### ISSUE THREAD

**Issue by StefanDavenport** [ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud#3]
The change log (https://blueprint.asd.gov.au/changelog/) only refers to this being v1.0 "Initial launch of ASD’s Blueprint for Secure Cloud, including Design documentation and Security templates.".  There is no change log reference to updates that have been made to the DTA Blueprint v2112 release.

It would be ideal if ASD could provide change references as part of taking over responsibility for the Blueprint and the updates made to the previous publication released by DTA.

**Comment by JollyRaccoon4** [comment]
Thanks @StefanDavenport 

Given the significant refresh of much of the content for ASD's Blueprint for Secure Cloud, we consider this to be a new product that replaces the previous Protected Utility Blueprint. Given this, we chose not to include the previous changelog on the current site. Users can access the content from the archived site at https://github.com/ASD-Blueprint/desktop.gov.au 

We are, however, developing an additional page that will further describe the key differences between the last version of the Protected Utility Blueprint and the first version of ASD's Blueprint for Secure Cloud. Please keep an eye out, and let us know if this helps!
