### ISSUE TITLE
Purview DLP Policy - Caution users distributing OFFICIAL: Sensitive information

### ISSUE THREAD

**Issue by jaybone2012** [ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud#33]
Hi,

Seeking clarification around the conditions in the DLP policy configuration "Caution users distributing OFFICIAL: Sensitive information"

I suspect this policy is intended to contain sensitivity labels, yet it contains sensitive info types instead.

This makes it similar to the "Limit disclosure of SENSITIVE information" policy which also contains the SIT's.

I look forward to your response.

**Comment by JollyRaccoon4** [comment]
Hi @jaybone2012 

Thanks for reaching out on this one. We are in the process of reviewing the issues and they will be fixed in an upcoming Purview-focused release that we are hoping to get out in January. 

Please continue to reach out if you have any further feedback or enquiries.
