### ISSUE TITLE
Configuration Scripts in static/content/files/configscripts are html not ps

### ISSUE THREAD

**Issue by martincaddick** [ASD-Blueprint/ASD-Blueprint-for-Secure-Cloud#5]
Looks like Block-certs.txt and OfficeMacroHardening-PreventActivationofOLE.txt are correct but the remainder of the scripts are html.

Please review.

**Comment by JollyRaccoon4** [comment]
Thanks @martincaddick - we have added this as a bug in our tracker, and will look to release a fix to ensure consistency as part of our next update.

**Comment by martincaddick** [comment]
@JollyRaccoon4 
I note that all except this one have been fixed now. Thx.
static/content/files/configscripts/autodisconnect.txt

**Comment by JollyRaccoon4** [comment]
Thanks @martincaddick  - this last one was also addressed as part of v1.2.1 released yesterday - please check it out and let us know if there are any further issues
